---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: beta
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - publishCmd: |
        docker buildx build \
          --output type=image,push=true \
          --platform "amd64,arm64,arm" \
          --tag lenra/devtools:${nextRelease.version} \
          --build-arg CI=true \
          --build-arg GH_PERSONNAL_TOKEN="${GITHUB_TOKEN}" \
          --cache-from type=local,src=~/.docker-cache \
          --cache-to type=local,dest=~/.docker-cache \
        .
  
