name: Elixir CI
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  checks:
    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
        # Start in localhost
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GH_PERSONNAL_TOKEN: ${{secrets.GH_PERSONNAL_TOKEN}}
      SHELL: /bin/bash
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.COMPONENTS_API_SSH }}
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.1" # Define the elixir version [required]
          otp-version: "24" # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile project
        run: mix compile
      - name: Check formatting
        run: mix format --check-formatted
      - name: Check code style with credo
        run: mix credo --strict
      - name: Run tests
        run: mix test
      - name: Run dialyzer
        run: mix dialyzer --format short
