name: Release
on:
  push:
    branches:
      - main
      - beta
      - "*.x"
env:
  flutter_version: "2.2.3"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GH_PERSONNAL_TOKEN: ${{secrets.GH_PERSONNAL_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set up Elixir
        uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
        with:
          elixir-version: "1.12"
          otp-version: "24"
      - name: Install Flutter & Dependencies
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.LENRA_CLIENT_SSH }}
            ${{ secrets.LENRA_UI_RUNNER_SSH }}
            ${{ secrets.LENRA_COMPONENTS_SSH }}
            ${{ secrets.COMPONENTS_API_SSH }}
      - name: Build Flutter Web
        run: |
          cd client
          flutter build web
          cd ..
      - name: Deps + compile elixir
        run: |
          cd server
          mix deps.get 
          mix compile
          cd ..
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: lenra/devtools:latest
          build-args: |
            GH_PERSONNAL_TOKEN=${{ secrets.GH_PERSONNAL_TOKEN }}
            CI=true
      - name: Setup node deps
        run: npm i conventional-changelog-conventionalcommits@4 @semantic-release/exec @semantic-release/git @semantic-release-plus/docker@2 -D
      - name: Release
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@18
