name: Release
on:
  push:
    branches:
      - main
      - beta
      - "*.x"
env:
  flutter_version: "3.3.x"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 50
    env:
      GH_PERSONNAL_TOKEN: ${{secrets.GH_PERSONNAL_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.1"
          otp-version: "24"
      - name: Install Flutter & Dependencies
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.LENRA_UI_RUNNER_SSH }}
            ${{ secrets.CLIENT_APP_SSH }}
            ${{ secrets.CLIENT_COMMON_SSH }}
            ${{ secrets.LENRA_COMPONENTS_SSH }}
      - name: Build Flutter Web
        run: |
          cd client
          flutter build web
          cd ..
      - name: Deps + compile elixir
        run: |
          cd server
          mix deps.get
          mix compile
          cd ..
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache docker build
        uses: actions/cache@v2
        with:
          path: ~/.docker-cache
          key: ${{ runner.os }}-docker
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          DOCKER_IMAGE: lenra/devtools
        run: npx --force -p conventional-changelog-conventionalcommits@5 -p @semantic-release/exec -p @semantic-release/git -p @semantic-release-plus/docker@2 -p semantic-release-export-data -p https://github.com/Tlepel/semantic-release.git#fix-versions-share-head semantic-release
