name: Release
on:
  push:
    branches:
      - main
      - beta
      - jonas-martinez/fix-docker-CI
      - "*.x"
env:
  flutter_version: "2.2.3"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Flutter & Dependencies
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
                ${{ secrets.LENRA_CLIENT_SSH }}
                ${{ secrets.LENRA_UI_RUNNER_SSH }}
                ${{ secrets.LENRA_COMPONENTS_SSH }}
      - name: Build Flutter Web
        run: |
          cd client
          flutter build web
          cd ..
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: devtools:latest
          build-args: |
            GH_PERSONNAL_TOKEN=${{ secrets.GH_PERSONNAL_TOKEN }}
            CI=true
      - name: Setup node deps
        run: npm i conventional-changelog-conventionalcommits @semantic-release/exec @semantic-release/git @semantic-release-plus/docker -D
      - name: Release
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
